name: 'Docker Build Action'
description: 'GitHub Action to build Docker images based on docker-build.yaml configuration'
author: 'frauniki'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  config-file:
    description: 'Path to the docker-build.yaml configuration file'
    required: false
    default: 'docker-build.yaml'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install js-yaml
      shell: bash
      run: npm install js-yaml

    - name: Parse docker-build.yaml
      id: parse-config
      uses: actions/github-script@v7
      with:
        script: |
          const parseConfig = require('./src/parse-config.js');
          return parseConfig('${{ inputs.config-file }}');

    # Docker Metadata and Build step removed as it was only used for Legacy Format

    - name: Process Multiple Builds
      uses: actions/github-script@v7
      with:
        script: |
          const processBuilds = require('./src/process-builds.js');
          const builds = JSON.parse('${{ steps.parse-config.outputs.builds }}');
          return processBuilds(builds);
