name: E2E Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
  # Adding a comment to trigger workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Docker Build Action
        uses: ./
        with:
          config-file: tests/fixtures/docker-build.yaml

      - name: Verify Docker image was built
        run: |
          # List Docker images to verify the image was built
          docker images
          
          # Check if our test image exists
          if docker images | grep -q "ghcr.io/frauniki/docker-build-action-test"; then
            echo "✅ Docker image was built successfully"
          else
            echo "❌ Docker image was not built"
            exit 1
          fi
          
          # Run the image to verify it works
          docker run --rm ghcr.io/frauniki/docker-build-action-test
          
          echo "E2E test completed successfully"
# Trigger workflow run for list format changes
# Re-run workflow after fixing core declaration
# Re-run workflow after fixing exec declaration
